Repository inf-lab-dev/labs, pull requests merged in 2024-12, with the labels that each got.

#15 Fix vitepress not rendering correct title
  index.md
Labels: bug

#17 Fix/solution tuesdays
  watermark/solution/tutorium_ML_temperature.solution.json
  watermark/solution/tutorium_ML_watermark.solution.json
Labels: solutions

#19 Add my solution for watermark
  watermark/solution/index.md
  watermark/solution/tutorium_PD_watermark.solution.json
Labels: solutions

#18 Add `errors` task
  errors/index.md
  errors/material/index.md
  errors/material/lab-errors.zip
  errors/material/make-zip.sh
  errors/material/scripts/setup.sh
  errors/material/scripts/word-list.py
  errors/material/task.md
  errors/material/template/search-zone.c
  errors/material/template/words-lectures-2-arrays-notes2.txt
  errors/material/template/words-lectures-3-algorithmen-notes3.txt
  errors/material/template/words-lectures-4-memory-notes4.txt
  index.md
Labels: task

#20 fixes some minor issues in the task description
  errors/material/task.md
Labels: bug

#22 Fixes segmentation fault in given c file
  errors/material/lab-errors.zip
  errors/material/template/words-lectures-2-arrays-notes2.txt
  errors/material/template/words-lectures-3-algorithmen-notes3.txt
  errors/material/template/words-lectures-4-memory-notes4.txt
Labels: bug

#23 Fix `errors` lab's special characters
  errors/material/lab-errors.zip
  errors/material/scripts/word-list.py
  errors/material/template/words-lectures-2-arrays-notes2.txt
  errors/material/template/words-lectures-3-algorithmen-notes3.txt
  errors/material/template/words-lectures-4-memory-notes4.txt
Labels: bug

#25 Add my solutions for `errors`
  errors/solution/tutorium_PD_errors.solution.json
Labels: solutions

#21 Add the `todo` task
  index.md
  todo/bonus/c-again.md
  todo/bonus/index.md
  todo/index.md
  todo/material/lab-todo.zip
  todo/material/make-zip.sh
  todo/material/scripts/setup.sh
  todo/material/template/test_todo.py
  todo/material/template/todo.c
  todo/material/template/todo.py
  todo/solution/index.md
  todo/task.md
Labels: task

#26 Fix template issues
  todo/material/lab-todo.zip
  todo/material/template/todo.py
  todo/task.md
Labels: bug

#27 add tuesday solution
  todo/solution/tests_tutorium_ML_todo.solution.json
  todo/solution/tutorium_ML_todo.solution.json
Labels: solutions
