Repository inf-lab-dev/labs, pull requests merged in 2024-11, with the labels that each got.

#1 Mark index page as home
  index.md
Labels: bug

#8 Add solutions
  snackbar/solution/tutorium_PD_snackbar.solution.json
Labels: solutions

#10 Add watermark to index page
  index.md
  watermark/material/lab-watermark.zip
Labels: bug

#12 lab solution added
  temperature/solution/index.md
  temperature/solution/tutorium_ML_temperature.solution.json
Labels: solutions

#13 Add my solution for `temperature`
  temperature/solution/tutorium_PD_temperature.solution.json
Labels: solutions

#14 Re-link watermark page and use new features
  index.md
Labels: enhancement
