Repository inf-lab-dev/labs, pull requests merged in 2025-01, with the labels that each got.

#28 Add my solutions for `todo`
  todo/solution/tests_tutorium_PD_todo.solution.json
  todo/solution/tutorium_PD_todo.solution.json
Labels: solutions

#29 add task weather
  index.md
  weather/bonus/filter.md
  weather/bonus/index.md
  weather/index.md
  weather/material/lab-weather.zip.json
  weather/material/template/city_weather.py
  weather/material/template/filter.py
  weather/material/template/main.py
  weather/material/template/weather_service.py
  weather/task.md
Labels: task

#30 Add references to `check50` in `weather`
  weather/bonus/filter.md
  weather/task.md
Labels: task

#31 add solution for weather
  weather/solution/filter_tutorium_ML_weather.solution.json
  weather/solution/index.md
  weather/solution/tutorium_ML_weather.solution.json
Labels: solutions

#34 Add my solutions to weather
  weather/solution/filter_turorium_PD_weather.solution.json
  weather/solution/tutorium_PD_weather.solution.json
Labels: solutions

#33 Adds the `watchlist` task
  watchlist/bonus/index.md
  watchlist/bonus/prettify/image.jpg
  watchlist/bonus/prettify/index.md
  watchlist/index.md
  watchlist/material/image/form.jpg
  watchlist/material/image/list-with-remove.jpg
  watchlist/material/image/list.jpg
  watchlist/material/lab-watchlist.zip.json
  watchlist/material/persistent-movies.js
  watchlist/material/template/index.html
  watchlist/task.md
Labels: task

#35 Adds the `watchlist` task to the index page
  index.md
  watchlist/material/persistent-movies.hosted.js
  watchlist/task.md
Labels: bug

#37 Add my solutions for `watchlist`
  watchlist/solution/index.md
  watchlist/solution/tutorium_PD_watchlist.solution.json
Labels: solutions

#36 Add `contact` task
  contact/bonus/delete/image.jpg
  contact/bonus/delete/index.md
  contact/bonus/index.md
  contact/index.md
  contact/material/image/error.jpg
  contact/material/image/form.jpg
  contact/material/image/view.jpg
  contact/material/lab-contact.zip.json
  contact/material/template/app.py
  contact/material/template/templates/error.html
  contact/material/template/templates/layout.html
  contact/task.md
  index.md
Labels: task

#38 Fix wrong material link in `contact`
  contact/task.md
Labels: bug

#39 add my solution for watchlist
  watchlist/solution/tutorium_ML_watchlist.solution.json
Labels: solutions

#40 add lab solutions
  contact/solution/error_tutorium_ML_contact.solution.json
  contact/solution/index.md
  contact/solution/index_tutorium_ML_contact.solution.json
  contact/solution/layout_tutorium_ML_contact.solution.json
  contact/solution/tutorium_ML_contact.solution.json
  contact/solution/view_tutorium_ML_contact.solution.json
Labels: solutions

#41 Add my solutions to `contact`
  contact/solution/error_tutorium_PD_contact.solution.json
  contact/solution/index_tutorium_PD_contact.solution.json
  contact/solution/layout_tutorium_PD_contact.solution.json
  contact/solution/tutorium_PD_contact.solution.json
  contact/solution/view_tutorium_PD_contact.solution.json
Labels: solutions
